name: fix

on: [push, pull_request, workflow_dispatch]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: git config user.name ${{ github.actor }}
      - run: git config user.email ${{ github.actor }}@users.noreply.github.com
      - run: npm ci
      - run: npm run format
      - run: git add .
      - run: git commit -m 'Format files' -a
      - run: git push
