name: fix

on: [push, pull_request, workflow_dispatch]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm ci
      - run: npm run format
      - run: git add .
      - run: git commit -m 'Format files' -a
      - run: git push
