name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Node.js ${{ matrix.node-version }} - ${{ matrix.os }}
    outputs:
      artifact: ${{ steps.pack.outputs.tarball }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Pack
        id: pack
        run: |
          echo "::set-output name=tarball::$(npm pack)"

        # run: npm pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: ${{ matrix.os }}-${{ matrix.node-version }}
          path: ./*.tgz

      - name: Did we fail?
        if: failure()
        run: ls -R

  test:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Download Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          path: ./
          name: ${{ matrix.os }}-${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Install Build Artifact
        run: npm install ${{ needs.build.outputs.artifact }}
        # run: npm install ./tiged-2.12.7.tgz

      - name: Erase TSConfig path aliases
        run: npx tsx scripts/eraseTSConfigPaths.mts

      - name: Run Tests
        run: npm test

      - name: Lint Files
        run: npm run lint

      - name: Did we fail?
        if: failure()
        run: ls -R
